name: AutoUpdate
on:
  schedule:
    - cron: '0 20 * * *' # 北京时间凌晨4点
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    # 这一段是强制开启写入权限，解决 403/128 错误
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true # 确保使用仓库自带的 TOKEN

      - name: Run Script
        run: python update.py

      - name: Commit and Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add tv.json
          git commit -m "Auto update tv config" || exit 0
          git push origin main
