name: AutoUpdate
on:
  schedule:
    - cron: '0 20 * * *' # 北京时间凌晨4点
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python update.py
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add tv.json
          git commit -m "update" || exit 0
          git push
